-- ACC-ARCH-P1-003: V1/V5 再実行パス向け。Flyway無効のH2でも楽観ロック列を揃える。
ALTER TABLE t_engineer ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 0;
ALTER TABLE m_customer ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 0;
ALTER TABLE t_work_record ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 0;
